server:
  port: 8081

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Qwert@1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

config:
  import: configserver:http://localhost:9296





