server:
  port: 9296
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anand-Thakar/spring-app-config.git
          clone-on-start: true
  application:
    name: CONFIG-SERVER

